# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='0.0', max_digits=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='0.0', max_digits=9),
        ),
    ]
