# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160623_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.TextField(blank=True, null=True),
        ),
    ]
