# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import msgs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reach', models.DecimalField(decimal_places=4, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to=msgs.models.mimg_location)),
                ('video', models.FileField(blank=True, null=True, upload_to=msgs.models.mvid_location)),
                ('audio', models.FileField(blank=True, null=True, upload_to=msgs.models.maudio_location)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
    ]
